spring.application.name=demoproduct
spring.datasource.url=jdbc:mysql://localhost:3306/demoproduct
spring.datasource.username=root
spring.datasource.password=Aa@123
spring.jpa.hibernate.ddl-auto=update
